name: Checks if files are present

on: [pull_request]

jobs:
  
  # This workflow contains a single job called "test"
  check_files:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check files script
        run: |
          chmod +x ./.github/check_run_scripts.sh
          ./.github/check_run_scripts.sh

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./filechk_results.txt
