name: Checks python code for linting

on: [pull_request]

jobs:
  
  # This workflow contains a single job called "test"
  check_pylint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install flake8
        run: pip install flake8
      - name: Python Linter
        uses: py-actions/flake8@v2
        with:
          ignore: "E402,E731,F541,W291,E122,E127,F401,E266,E241,C901,E741,W293,F811,W503,E203,F403,F405,B007"
          max-line-length: "150"
          path: "src"
          plugins: "flake8-bugbear==22.1.11"
