name: Checks python code for linting

on: [pull_request]

jobs:
  
  # This workflow contains a single job called "test"
  check_pylint:

    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v3
      - uses: actions/checkout@v4
      - name: Install flake8
        run: pip install flake8
      - name: Python Linter
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
          path: "src"
          args: "--max-line-length=120 --ignore=E402,E731,F541,W291,E122,E127,F401,E266,E241,C901,E741,W293,F811,W503,E203"
      #- name: GitHub Action for pylint
      #  uses: marian-code/python-lint-annotate@v3
